version: '3.8'

services:
  app:
    build: .
    container_name: mailwatcher_app
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      # Mount source code for live development
      - .:/app
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py shell -c 'from django.contrib.auth.models import User; User.objects.filter(username=\"admin\").exists() or User.objects.create_superuser(\"admin\", \"admin@example.com\", \"admin\")' &&
             python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

  scheduler:
    build: .
    container_name: mailwatcher_scheduler
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      # Mount source code for live development
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate &&
             python manage.py start_email_scheduler"
    restart: unless-stopped
    depends_on:
      - app

volumes:
  logs:
  media: