# Generated by Django 5.2.6 on 2025-09-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnreadOnlyNoMarkMailbox',
            fields=[
            ],
            options={
                'verbose_name': 'Unread-Only No-Mark Mailbox',
                'verbose_name_plural': 'Unread-Only No-Mark Mailboxes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_mailbox.mailbox',),
        ),
    ]
